Trying to make the external monitor switching to be smarter

diff --git a/bin/external b/bin/external
--- a/bin/external
+++ b/bin/external
@@ -1,20 +1,40 @@
-setxkbmap -option ctrl:nocaps  
-xmodmap ~/.Xmodmap
+#!/bin/sh
 
-xrdb -merge ~/.Xresources
+prog=$( basename $0 )
+internal=$( xrandr | grep primary | awk ' { print $1 }' )
+external=$( xrandr | grep -v primary | grep \ connected | awk ' { print $1 }' )
+
+[ -z "$external" ] && echo "Can't find external monitor with xrandr. Exiting" && exit 1
+[ -z "$internal" ] && echo "Can't find internal monitor with xrandr. Exiting" && exit 1
+
+orient=${1:-portrait}
+dual=$2
+
 portrait() {
-  xrandr --output VGA1 --auto --mode 1600x1200 --rotate left --output LVDS1 --off #--auto --left-of VGA1
+  echo xrandr --output $external --auto --mode 1600x1200 --rotate left --output $internal $opts
 }
 landscape() {
-  xrandr --output VGA1 --auto --mode 1600x1200 --output LVDS1 --off #--auto --left-of VGA1
+  echo xrandr --output $external --auto --mode 1600x1200 --output $internal $opts
 }
-#portrait
-landscape
-xrandr --dpi 96
-#xrandr --output VGA1 --auto --mode 1600x1200 --output LVDS1 --off #--auto --left-of VGA1
-#xrandr --output VGA1 --auto --output LVDS1 --off
-sleep 1
-pkill notion
-sleep 1
-notion&
-echo $?
+
+if [ $dual ]; then
+  opts="--auto --left-of $external"
+else
+  opts="--off"
+fi
+
+eval $orient
+if [ $? ] ; then
+  setxkbmap -option ctrl:nocaps  
+  xmodmap ~/.Xmodmap
+  xrdb -merge ~/.Xresources
+
+  xrandr --dpi 75
+
+  sleep 1
+  pkill notion
+  sleep 1
+  notion&
+else
+  echo "Failed"
+fi
